_format_version: "1.1"

services:
  # auth-service
- name: auth
  url: http://192.168.2.6:8081
  routes:
  - name: auth
    paths:
    - /auth

  # status-service
- name: status
  url: http://192.168.2.6:8080
  routes:
  - name: status
    paths:
    - /status

plugins:
- name: rate-limiting
  config: 
    minute: 50
    hide_client_headers: true

- name: response-transformer
  config:
     add:
      headers:
      - Gateway-API:Kong-Gateway-API

